import type {
  Industry,
  Leaderboard,
  LeaderboardCategory,
  PlatformInfo,
} from '@/leaderboard';

export const VISIBLE_TURKEY: LeaderboardCategory = {
  'enterprise-software': [
    {
      rank: 1,
      company: 'Logo Yazilim',
      topPlatform: 'google',
      visibilityScore: 3.23,
      mentions: 48,
      averagePosition: 1.04,
      averageSentiment: 60.7,
      domain: 'logo.com.tr',
    },
    {
      rank: 2,
      company: 'GlassHouse',
      topPlatform: 'google',
      visibilityScore: 2.09,
      mentions: 31,
      averagePosition: 1.84,
      averageSentiment: 64.65,
      domain: 'glasshouse.com.tr',
    },
    {
      rank: 3,
      company: 'KocSistem',
      topPlatform: 'google',
      visibilityScore: 0.94,
      mentions: 14,
      averagePosition: 1.73,
      averageSentiment: 61.92,
      domain: 'kocsistem.com.tr',
    },
    {
      rank: 4,
      company: 'KocSistem Cloud',
      topPlatform: 'google',
      visibilityScore: 0.78,
      mentions: 11,
      averagePosition: 2.42,
      averageSentiment: 54.72,
      domain: 'kocsistem.com.tr',
    },
    {
      rank: 5,
      company: 'OBSS',
      topPlatform: 'google',
      visibilityScore: 0.74,
      mentions: 11,
      averagePosition: 2.94,
      averageSentiment: 54.72,
      domain: 'obss.com.tr',
    },
  ],
  'digital-commerce': [
    {
      rank: 1,
      company: 'Trendyol',
      topPlatform: 'perplexity',
      visibilityScore: 2.76,
      mentions: 41,
      averagePosition: 1.37,
      domain: 'trendyol.com',
    },
    {
      rank: 2,
      company: 'Hepsiburada',
      topPlatform: 'perplexity',
      visibilityScore: 2.63,
      mentions: 39,
      averagePosition: 1.96,
      averageSentiment: 62.68,
      domain: 'hepsiburada.com',
    },
    {
      rank: 3,
      company: 'n11',
      topPlatform: 'google',
      visibilityScore: 1.21,
      mentions: 18,
      averagePosition: 2.43,
      averageSentiment: 62.86,
      domain: 'n11.com',
    },
    {
      rank: 4,
      company: 'Amazon Turkiye',
      topPlatform: 'perplexity',
      visibilityScore: 0.88,
      mentions: 13,
      averagePosition: 3.44,
      averageSentiment: 68.08,
      domain: 'amazon.com.tr',
    },
  ],
  'utilities-energy': [
    {
      rank: 1,
      company: 'Aksa Dogalgaz',
      topPlatform: 'perplexity',
      visibilityScore: 2.29,
      mentions: 33,
      averagePosition: 1.0,
      averageSentiment: 76.07,
      domain: 'aksadogalgaz.com.tr',
    },
    {
      rank: 2,
      company: 'IGDAS',
      topPlatform: 'google',
      visibilityScore: 1.08,
      mentions: 16,
      averagePosition: 1.25,
      averageSentiment: 50.48,
      domain: 'igdas.istanbul',
    },
  ],
  telecommunications: [
    {
      rank: 1,
      company: 'DorukNet',
      topPlatform: 'google',
      visibilityScore: 1.01,
      mentions: 15,
      averagePosition: 1.67,
      averageSentiment: 58.7,
      domain: 'doruk.net.tr',
    },
    {
      rank: 2,
      company: 'Vodafone Business Cloud',
      topPlatform: 'openai',
      visibilityScore: 0.81,
      mentions: 12,
      averagePosition: 1.64,
      averageSentiment: 50.33,
      domain: 'vodafone.com.tr',
    },
  ],
  'consumer-electronics': [
    {
      rank: 1,
      company: 'Exper',
      topPlatform: 'perplexity',
      visibilityScore: 0.92,
      mentions: 13,
      averagePosition: 1.53,
      averageSentiment: 59.67,
      domain: 'exper.com.tr',
    },
    {
      rank: 2,
      company: 'General Mobile',
      topPlatform: 'google',
      visibilityScore: 0.81,
      mentions: 12,
      averagePosition: 1.62,
      averageSentiment: 50.33,
      domain: 'generalmobile.com',
    },
    {
      rank: 3,
      company: 'Monster Notebook',
      topPlatform: 'google',
      visibilityScore: 0.74,
      mentions: 11,
      averagePosition: 2.69,
      averageSentiment: 58.82,
      domain: 'monsternotebook.com.tr',
    },
    {
      rank: 4,
      company: 'Reeder',
      topPlatform: 'google',
      visibilityScore: 0.74,
      mentions: 11,
      averagePosition: 3.25,
      averageSentiment: 65.63,
      domain: 'reeder.com.tr',
    },
    {
      rank: 5,
      company: 'Samsung Turkiye',
      topPlatform: 'google',
      visibilityScore: 0.61,
      mentions: 9,
      averagePosition: 2.5,
      averageSentiment: 59.5,
      domain: 'samsung.com',
    },
  ],
  'on-demand-services': [
    {
      rank: 1,
      company: 'Getir',
      topPlatform: 'openai',
      visibilityScore: 0.74,
      mentions: 11,
      averagePosition: 1.89,
      averageSentiment: 58.82,
      domain: 'getir.com',
    },
    {
      rank: 2,
      company: 'Yemeksepeti',
      topPlatform: 'openai',
      visibilityScore: 0.65,
      mentions: 9,
      averagePosition: 3.29,
      averageSentiment: 60.45,
      domain: 'yemeksepeti.com',
    },
  ],
  'financial-services': [
    {
      rank: 1,
      company: 'Garanti BBVA',
      topPlatform: 'gemini',
      visibilityScore: 58.92,
      domain: 'garantibbva.com.tr',
    },
    {
      rank: 2,
      company: 'Akbank',
      topPlatform: 'chatgpt',
      visibilityScore: 49.37,
      domain: 'akbank.com',
    },
    {
      rank: 3,
      company: 'Isbank',
      topPlatform: 'copilot',
      visibilityScore: 45.21,
      domain: 'isbank.com.tr',
    },
    {
      rank: 4,
      company: 'Papara',
      topPlatform: 'grok',
      visibilityScore: 33.4,
      domain: 'papara.com',
    },
    {
      rank: 5,
      company: 'Fibabanka',
      topPlatform: 'google-ai-overviews',
      visibilityScore: 28.75,
      domain: 'fibabanka.com.tr',
    },
    {
      rank: 6,
      company: 'Enpara',
      topPlatform: 'gemini',
      visibilityScore: 24.63,
      domain: 'enpara.com',
    },
    {
      rank: 7,
      company: 'Param',
      topPlatform: 'perplexity',
      visibilityScore: 22.18,
      domain: 'param.com.tr',
    },
    {
      rank: 8,
      company: 'Paycell',
      topPlatform: 'copilot',
      visibilityScore: 19.6,
      domain: 'paycell.com.tr',
    },
    {
      rank: 9,
      company: 'Tosla',
      topPlatform: 'grok',
      visibilityScore: 16.47,
      domain: 'tosla.com',
    },
    {
      rank: 10,
      company: 'Moka Ödeme',
      topPlatform: 'google-ai-mode',
      visibilityScore: 12.94,
      domain: 'moka.com',
    },
  ],
  telecommunications: [
    {
      rank: 1,
      company: 'Türk Telekom',
      topPlatform: 'gemini',
      visibilityScore: 82.61,
      domain: 'turktelekom.com.tr',
    },
    {
      rank: 2,
      company: 'Turkcell',
      topPlatform: 'chatgpt',
      visibilityScore: 75.08,
      domain: 'turkcell.com.tr',
    },
    {
      rank: 3,
      company: 'Vodafone Türkiye',
      topPlatform: 'perplexity',
      visibilityScore: 69.91,
      domain: 'vodafone.com.tr',
    },
    {
      rank: 4,
      company: 'TürkNet',
      topPlatform: 'grok',
      visibilityScore: 47.34,
      domain: 'turk.net',
    },
    {
      rank: 5,
      company: 'Millenicom',
      topPlatform: 'google-ai-mode',
      visibilityScore: 31.76,
      domain: 'millenicom.com.tr',
    },
    {
      rank: 6,
      company: 'GIBIRNet',
      topPlatform: 'copilot',
      visibilityScore: 23.51,
      domain: 'gibir.net',
    },
    {
      rank: 7,
      company: 'Kablonet',
      topPlatform: 'gemini',
      visibilityScore: 20.84,
      domain: 'kablonet.com.tr',
    },
    {
      rank: 8,
      company: 'TT Mobil',
      topPlatform: 'chatgpt',
      visibilityScore: 18.27,
      domain: 'ttmobil.com.tr',
    },
    {
      rank: 9,
      company: 'Bimcell',
      topPlatform: 'perplexity',
      visibilityScore: 15.63,
      domain: 'bimcell.com.tr',
    },
    {
      rank: 10,
      company: 'PoyrazNet',
      topPlatform: 'grok',
      visibilityScore: 11.42,
      domain: 'poyraznet.com',
    },
  ],
};

export const RISING_TURKEY: LeaderboardCategory = {
  'software-companies': [
    {
      rank: 122,
      company: 'Bunsar',
      topPlatform: 'google-ai-mode',
      visibilityScore: 2.14,
      change: 68,
    },
    {
      rank: 131,
      company: 'Faladdin',
      topPlatform: 'perplexity',
      visibilityScore: 1.93,
      change: 61,
    },
    {
      rank: 146,
      company: 'Scotty',
      topPlatform: 'chatgpt',
      visibilityScore: 1.71,
      change: 54,
    },
    {
      rank: 158,
      company: 'Vivense Tech',
      topPlatform: 'gemini',
      visibilityScore: 1.48,
      change: 48,
    },
    {
      rank: 174,
      company: 'Hepsijet',
      topPlatform: 'grok',
      visibilityScore: 1.22,
      change: 42,
    },
  ],
  'financial-services': [
    {
      rank: 64,
      company: 'Midas',
      topPlatform: 'gemini',
      visibilityScore: 2.35,
      change: 37,
      domain: 'getmidas.com',
    },
    {
      rank: 78,
      company: 'Colendi',
      topPlatform: 'copilot',
      visibilityScore: 2.02,
      change: 33,
      domain: 'colendi.com',
    },
    {
      rank: 81,
      company: 'Figopara',
      topPlatform: 'perplexity',
      visibilityScore: 1.88,
      change: 29,
      domain: 'figopara.com',
    },
    {
      rank: 89,
      company: 'Tarfin',
      topPlatform: 'google-ai-overviews',
      visibilityScore: 1.71,
      change: 26,
      domain: 'tarfin.com',
    },
    {
      rank: 94,
      company: 'Apsiyon',
      topPlatform: 'chatgpt',
      visibilityScore: 1.49,
      change: 22,
      domain: 'apsiyon.com',
    },
  ],
  telecommunications: [
    {
      rank: 44,
      company: 'Superonline',
      topPlatform: 'gemini',
      visibilityScore: 3.12,
      change: 19,
      domain: 'superonline.net',
    },
    {
      rank: 49,
      company: 'Netspeed',
      topPlatform: 'perplexity',
      visibilityScore: 2.76,
      change: 17,
      domain: 'netspeed.com.tr',
    },
    {
      rank: 53,
      company: 'Turkcell Platinum',
      topPlatform: 'google-ai-mode',
      visibilityScore: 2.41,
      change: 14,
      domain: 'turkcell.com.tr',
    },
    {
      rank: 56,
      company: 'Vodafone Red',
      topPlatform: 'grok',
      visibilityScore: 2.18,
      change: 12,
      domain: 'vodafone.com.tr',
    },
    {
      rank: 63,
      company: 'Türk Telekom Prime',
      topPlatform: 'chatgpt',
      visibilityScore: 1.97,
      change: 11,
      domain: 'turktelekom.com.tr',
    },
  ],
};

export const TRENDING_TURKEY: LeaderboardCategory = {};

export const LEADERBOARD_TURKEY: Leaderboard = {
  visible: VISIBLE_TURKEY,
  rising: RISING_TURKEY,
  trending: TRENDING_TURKEY,
};

export const INDUSTRIES_TURKEY: Record<string, Industry> = {
  'enterprise-software': {
    id: 'enterprise-software',
    displayName: 'Enterprise Software',
  },
  'digital-commerce': {
    id: 'digital-commerce',
    displayName: 'Digital Commerce',
  },
  'utilities-energy': {
    id: 'utilities-energy',
    displayName: 'Utilities & Energy',
  },
  telecommunications: {
    id: 'telecommunications',
    displayName: 'Telecommunications',
  },
  'consumer-electronics': {
    id: 'consumer-electronics',
    displayName: 'Consumer Electronics',
  },
  'on-demand-services': {
    id: 'on-demand-services',
    displayName: 'On-demand Services',
  },
  'financial-services': {
    id: 'financial-services',
    displayName: 'Financial Services',
  },
};

export const PLATFORMS_TURKEY: Record<string, PlatformInfo> = {
  chatgpt: {
    displayName: 'ChatGPT',
    website: 'https://chat.openai.com',
    domain: 'openai.com',
  },
  google: {
    displayName: 'Google',
    domain: 'google.com',
  },
  openai: {
    displayName: 'OpenAI',
    website: 'https://platform.openai.com',
    domain: 'openai.com',
  },
  gemini: {
    displayName: 'Gemini',
    website: 'https://gemini.google.com',
    domain: 'gemini.google.com',
  },
  'google-ai-mode': {
    displayName: 'Google AI Mode',
    domain: 'google.com',
  },
  'google-ai-overviews': {
    displayName: 'Google AI Overviews',
    domain: 'google.com',
  },
  copilot: {
    displayName: 'Copilot',
    website: 'https://copilot.microsoft.com',
    domain: 'copilot.microsoft.com',
  },
  perplexity: {
    displayName: 'Perplexity',
    website: 'https://www.perplexity.ai',
    domain: 'perplexity.ai',
  },
  grok: {
    displayName: 'Grok',
    domain: 'x.ai',
  },
};
